before_script:
           - docker info
           - docker login -e philario@catalystdevworks.com -u catalystdevlabs -p q1w2e3r4t5

         build:
           script:
             - mvn clean package docker:build
             - docker push catalystdevlabs/aperture-data
           only:
             - master
           tags:
             - docker
             - aws